export const keys = {
    accreditationPeriodList: "لیست دوره های اعتباربخشی",
    row: "ردیف",
    accreditationListTitle: "عنوان دوره اعتباربخشی",
    creationTime: "زمان ایجاد",
    timeOfLastEdit: "زمان آخرین ویرایش",
    createBy: "ایجاد توسط",
    lastEditBy: "آخرین ویرایش توسط",
    periodLength: "طول دوره",
    status: "وضعیت",
    operation: "عملیات",
    betweenTwoTime: (start, end) => `از ${start} تا ${end}`,
    recalculateResult: "محاسبه مجدد نتایج",
    quickAccessSanjeh: "دسترسی سریع به سنجه ها",
    mehvars: "محورها",
    copyOfPeriod: "کپی از دوره",
    filter: "فیلتر",
    back: "بازگشت",
    createAccreditation: "ایجاد دوره اعتبار بخشی",
    fromDate: "از تاریخ",
    toDate: "تا تاریخ",
    addAccreditationPeriod: "اضافه کردن دوره اعتبار بخشی",
    requiredField: "این فیلد ضروری است",
    thisTimeMustBeAfterStart: "این تاریخ باید بعد از تاریخ شروع باشد",
    cleanForm: "خالی کردن فرم",
    save: "ذخیره",
    currentPeriod: "دوره جاری",
    orgType: "نوع سازمان",
    sort: "ترتیب",
    positiveNumber: "مقدار این فیلد باید بیشتر از صفر باشد",
    mustNumber: "مقدار وارد شده باید یک عدد باشد",
    accreditationAdded: "دوره اعتباربخشی با موفقیت اضافه شد",
    operationFail: "خطا در انجام عملیات. دوباره تلاش کنید",
    edit: "ویرایش",
    delete: "حذف",
    successOperation: "عملیات مورد نظر با موفقیت انجام شد"

};