export const keys = {
    accreditationPeriodList: "لیست دوره های اعتباربخشی",
    row: "ردیف",
    accreditationListTitle: "عنوان دوره اعتباربخشی",
    creationTime: "زمان ایجاد",
    timeOfLastEdit: "زمان آخرین ویرایش",
    createBy: "ایجاد توسط",
    lastEditBy: "آخرین ویرایش توسط",
    periodLength: "طول دوره",
    status: "وضعیت",
    operation: "عملیات",
    betweenTwoTime: (start, end) => `از ${start} تا ${end}`,
    recalculateResult: "محاسبه مجدد نتایج",
    quickAccessSanjeh: "دسترسی سریع به سنجه ها",
    mehvars: "محورها",
    copyOfPeriod: "کپی از دوره",
    filter: "فیلتر",
    back: "بازگشت",
    createAccreditation: "ایجاد دوره اعتبار بخشی",
    fromDate: "از تاریخ",
    toDate: "تا تاریخ",
    addAccreditationPeriod: "اضافه کردن دوره اعتبار بخشی",
    requiredField: "این فیلد ضروری است",
    thisTimeMustBeAfterStart: "این تاریخ باید بعد از تاریخ شروع باشد",
    cleanForm: "خالی کردن فرم",
    save: "ذخیره",
    currentPeriod: "دوره جاری",
    orgType: "نوع سازمان",
    sort: "ترتیب",
    positiveNumber: "مقدار این فیلد باید بیشتر از صفر باشد",
    mustNumber: "مقدار وارد شده باید یک عدد باشد",
    accreditationAdded: "دوره اعتباربخشی با موفقیت اضافه شد",
    operationFail: "خطا در انجام عملیات. دوباره تلاش کنید",
    edit: "ویرایش",
    delete: "حذف",
    successOperation: "عملیات مورد نظر با موفقیت انجام شد",
    welcomeToLogin: "به صفحه لاگین خوش آمدید",
    notRegisterYet: "هنوز ثبت نام نکرده اید؟",
    register: "ثبت نام",
    login: "ورود",
    userName: "نام کاربری",
    password: "رمزعبور",
    email: "ایمیل",
    forgetPassword: "رمز عبور خود را فراموش کرده اید؟",
    successLogin: "ورود با موفقیت انجام شد",
    axisList: "لیست محورها",
    createAxis: "ایجاد محور",
    axisTitle: "عنوان محور",
    weightingFactor: "ضریب وزنی",
    accreditationTitle: "دوره اعتباربخشی",
    addAxisSuccess: "محور با موفقیت اضافه شد",
    successChangeStatusAxis: "وضعیت محور با موفقیت تغییر کرد",
    editSuccess: "ویرایش با موفقیت انجام شد",
    order: "ترتیب",
    weightedCoefficient: "ضریب وزنی",
    numberOnly: "این فیلد باید عدد باشد",
    subAxis: "زیرمحور",
    subAxisList: "لیست زیرمحور",
    createSubAxis: "ایجاد زیرمحور",
    subAxisTitle: "عنوان زیرمحور",
    standards: "استانداردها",
    editSubAxis: "ویرایش زیرمحور",
    standardList: "لیست استاندارد",
    createStandard: "ایجاد استاندارد",
    editStandard: "ویرایش استاندارد",
    standardTitle: "عنوان استاندارد",
    standardCode: "کداستاندارد",
    gauges: "سنجه ها",
    addStandardSuccess: "استاندارد با موفقیت اضافه شد",
    standardChangeStatus: "وضعیت استاندارد با موفقیت تغییر کرد"


};